// Copyright 2021 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package thriftgo

import (
	"github.com/cloudwego/thriftgo/parser"
)

type streamingInterfaceTemplateData struct {
	Version  string
	PkgName  string
	Services []*parser.Service
}

var streamingInterfaceTemplate = `
{{- define "streaming"}}
// Code generated by Kitex {{ .Version}}. DO NOT EDIT.
package {{ .PkgName}}

import (
	"context"

	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var _ context.Context

{{- range .Services }}
{{$serviceName := .Name}}
type {{.Name}} interface {
{{- range .Functions}}
{{$arg := index .Arguments 0}}
{{$RequestType := $arg.Type}}
{{$ResponseType := .FunctionType.Name}}
{{if or .ClientStreaming .ServerStreaming}}
	{{.Name}}({{if and .ServerStreaming (not .ClientStreaming)}}req *{{$RequestType}}, {{end}}stream {{$serviceName}}_{{.Name}}Server) (err error)
{{else}}
	{{.Name}}(ctx context.Context{{range .Arguments}}, {{.Name}} *{{.Type}}{{end}}) (res *{{$ResponseType}}, err error)
{{end}}
{{end}}{{/* range Functions */}}
}
{{- range .Functions}}
{{$arg := index .Arguments 0}}
{{$RequestType := $arg.Type.Name}}
{{$ResponseType := .FunctionType.Name}}
{{- if or .ClientStreaming .ServerStreaming}}
type {{$serviceName}}_{{.Name}}Server interface {
	streaming.Stream
	{{if .ClientStreaming}}
	Recv() (*{{$RequestType}}, error)
	{{end}}
	{{if .ServerStreaming}}
	Send(*{{$ResponseType}}) error
	{{end}}
	{{if and .ClientStreaming (not .ServerStreaming)}}
	SendAndClose(*{{$ResponseType}}) error
	{{end}}
}
{{- end}}
{{- end}}{{/* range .Functions */}}
{{- end}}{{/* range .Service */}}
{{- end}}{{/* define streaming*/}}
`
